
export enum DESIGNER_EVENT {
  ENABLE = 'ENABLE',
  DISABLE = 'DISABLE',
  CREATE_MODE = 'CREATE_MODE',
  DELETE_MODE = 'DELETE_MODE',
  SELECT = 'SELECT',
  DESELECT = 'DESELECT',
  PALETTE_SELECT_START = 'PALETTE_SELECT_START',
  PALETTE_SELECT_END = 'PALETTE_SELECT_END',
}