
export enum DESIGNER_EVENT {
  ENABLE = 'ENABLE',
  DISABLE = 'DISABLE',
  RESET = 'RESET',
  PREVIEW = 'PREVIEW',
  CREATE = 'CREATE',
  SELECT = 'SELECT',
  DESELECT = 'DESELECT',
  DELETE = 'DELETE',
  PALETTE_SELECT_START = 'PALETTE_SELECT_START',
  PALETTE_SELECT_END = 'PALETTE_SELECT_END',
}