
export enum TOOL_EVENT {
  DEFAULT = 'DEFAULT',
  CREATE_GATE = 'CREATE_GATE',
  DELETE_GATE = 'DELETE_GATE',
  BEGIN_SELECTION = 'BEGIN_SELECTION',
  MOVE_SELECTION = 'MOVE_SELECTION',
  CREATE_WIRE = 'CREATE_WIRE',
  DELETE_WIRE = 'DELETE_WIRE'
}